@startuml "Login"

class "LoginView" <<View>>{
    - mLoginViewModel : LoginViewModel
    + start(Stage) : void
}
class "LoginViewModel" <<ViewModel>>{

}

class UserModel <<Model>> {
    - userId : String
    - userName : String
    - userEmail : String
    - userPassword : String

    + getUserId() : String
    + setUserID(userId:String):void
    + getUserName() :String
    + setUserName(userName:String): void
    + getuserEmail(): String
    + setuserEmail(userEmail:String): void
    + getuserPassword():void
    + setuserPassword(userPassword:String) : void
}


@enduml